version: "3"

services:
  postgres:
    image: postgres:14.5
    volumes:
      - /data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=bmconso
      - POSTGRES_USER=bmconso
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - bmconso-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend/database
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /data/appli:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bmconso
      - POSTGRES_USER=bmconso
      - POSTGRES_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - bmconso-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=grand_dan2@yahoo.fr
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "5050:80"
    networks:
      - bmconso-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - postgres:postgres:14.1
      - pgadmin:pgadmin4
    container_name: bmconsowebapp
    restart: always
    networks:
      - bmconso-network
  
  networks:
    bmconso-network:
      driver: bridge  