# Generated by Django 3.2.6 on 2022-09-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmconso', '0002_auto_20220923_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='hour_begin',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='rule',
            name='hour_end',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
